version: '3'
services:
  cassandra-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-node1
    ports:
      - 9042:9042
    volumes:
      - cassandra-data1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1 ##,cassandra-node2,cassandra-node3
    expose:
      # Intra-node communication
      - 7000
      # TLS intra-node communication
      - 7001
      # JMX
      - 7199
      # CQL
      - 9042
      # CQL SSL
      - 9142
      - 9160

volumes:
  cassandra-data1:
    # cassandra-node2:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   container_name: cassandra-node2
    #   ports:
    #     - 9043:9042
    #   volumes:
    #     - cassandra-data2:/var/lib/cassandra
    #   environment:
    #     - CASSANDRA_CLUSTER_NAME=MyCluster
    #     - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    #   expose:
    #     # Intra-node communication
    #     - 7000
    #     # TLS intra-node communication
    #     - 7001
    #     # JMX
    #     - 7199
    #     # CQL
    #     - 9042
    #     # CQL SSL
    #     - 9142
    #     - 9160

    # cassandra-node3:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   container_name: cassandra-node3
    #   ports:
    #     - 9044:9042
    #   volumes:
    #     - cassandra-data3:/var/lib/cassandra
    #   environment:
    #     - CASSANDRA_CLUSTER_NAME=MyCluster
    #     - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    #   expose:
    #     # Intra-node communication
    #     - 7000
    #     # TLS intra-node communication
    #     - 7001
    #     # JMX
    #     - 7199
    #     # CQL
    #     - 9042
    #     # CQL SSL
    #     - 9142
    #     - 9160


    # cassandra-data2:
    # cassandra-data3:

