version: '3'
services:
  cassandra-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-node1
    volumes:
      - cassandra-data1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.101

  cassandra-node2:
    cassandra-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - cassandra-data2:/var/lib/cassandra
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.102

  cassandra-node3:
    cassandra-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - cassandra-data3:/var/lib/cassandra
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.103

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: "192.168.0.1"

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:
